sources:
  npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

reviewed:
  npm:
    - "@buf/blacksmith_vm-agent.bufbuild_es"
    - "@buf/blacksmith_vm-agent.connectrpc_es"
    - "@bufbuild/protobuf"